// <auto-generated />
using HotelListing_webAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing_webAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220220083522_SeedingDatabase")]
    partial class SeedingDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HotelListing_webAPI.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "UnitedStates",
                            ShortName = "US"
                        },
                        new
                        {
                            Id = 2,
                            Name = "UnitedKingdom",
                            ShortName = "UK"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Norway",
                            ShortName = "NW"
                        });
                });

            modelBuilder.Entity("HotelListing_webAPI.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "LA/Beverly Hills",
                            CountryId = 1,
                            Name = "spinas",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "london",
                            CountryId = 2,
                            Name = "five star",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "capital",
                            CountryId = 3,
                            Name = "grand hotel",
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("HotelListing_webAPI.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing_webAPI.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
